### ISSUE TITLE
Extend use of opposite-of and any sub-predicates to connect relevant RO/biolink predicates

### ISSUE THREAD

**Issue by bill-baumgartner** [NCATSTranslator/opposites#1]
This is an umbrella issue geared towards coordinating use of the opposite-of relation in RO/biolink.

- [x] biolink/biolink-model#657
- [x] biolink/biolink-model#656

**Comment by nlharris** [comment]
- [ ] biolink/biolink-model#657
- [ ] biolink/biolink-model#656

**Comment by nlharris** [comment]
- [ ] thing 1
- [ ] thing 2
